descriptions = {
    "A": """Utilise your skills in data integration and SQL data warehouse development Benefit from professional development and training in a coastal, city location
    Temporary 12 month full time role - 80 hours per fortnight (salary packaging + super+ RDO) Area Profile Sitting within one of Victoria’s six regional health centres, Barwon Health serves the community of Greater Geelong and beyond. Victoria’s second largest city after Melbourne! We serve over 500,000 people through the efforts of over 8,000 staff and more than 1200 volunteers.
    Enjoy the range of lifestyle choices Geelong has to offer including inner city, coastal, suburban and rural homes at affordable prices and high standard of schooling options throughout the area. You will appreciate the beautiful parks, rivers, walks and wineries.
    About The Facility Barwon Health is the largest regional health service in Victoria with over 8000 employees and 22 sites. Services include maternity services, acute care, mental health services, rehabilitation, urgent care, community care and aged care. The primarily on-premise data warehouse, integration and reporting platform is built on contemporary Microsoft Business Intelligence technology. The data warehouse and extensive data lake supports analytical, operational, research/audit and statutory reporting requirements.
    About The Role In this role you will support Barwon Health’s current and evolving needs in a timely and strategically aligned manner, through the development and maintenance of data integration processes and SQL Server database objects within the data warehouse and data lake.
    To be successful in this role you will have extensive contemporary knowledge and experience in the Microsoft Business Intelligence stack, in particular T-SQL, SSIS and SSAS. Familiarity with Master Data Service’s integration will be an advantage.
    The Business Intelligence Unit is a small team of highly skilled professionals with broad roles and responsibility for enterprise wide operational and analytical reporting. The team work collaboratively to support business users and are committed to ongoing professional development. Familiarity with and experience working in the Victorian Public Health system and the ability to manage competing demands through effective prioritisation is desirable.
    About The Culture Information and Analytics is a dynamic vibrant environment in which to work - our only constant is change. Providing high-quality Information Services that underpin our clinical systems is our shared passion. We are a happy, friendly team and always striving to improve our service delivery.
    We are a team that embraces change and are always looking for innovative ideas to improve our team and the organisation.Barwon Health Staff Benefits
    Flexible working arrangements Professional development Access to employee wellness facility Salary packaging al club Diversity and Inclusion
    At Barwon Health we are committed to a diverse and inclusive workforce where we value each person’s uniqueness. We embrace diverse life experiences and the perspectives of our people, whilst providing high-quality health care to all members of our community, regardless of age, gender, ethnicity, religion, cultural background, disability, or sexual orientation.
    At Barwon Health we are committed to providing positive employment opportunities for Aboriginal and Torres Strait Islander people and welcome employment applications from candidates of Aboriginal and Torres Strait Islander background.
    We at Barwon Health strongly encourage people with disability and diverse backgrounds to apply for our roles.
    If we can assist you with any reasonable adjustments in order to submit your application for this role, please contact the Talent Acquisition team via email at talent.acquisition@barwonhealth.org.au noting your preferred method of communication and contact details and a member of the team will be in touch.
    We Barwon Health are proud to be Totally Smoke Free. Applicants for this role must be fully vaccinated for Covid-19 and meet the requirements of the Barwon Health immunisation policy.""",

    "B":"""About the job $86,247 to $99,027 (APS 6) plus 15.4% super Champion industry best practice Flexibility to provide work/life balance
    About the role a Data Analyst, you’ll analyse and interpret a range of data and information to inform decision-making and strategy development. You will actively review current processes and procedures to identify improvement opportunities and recommend solutions.
    Your duties Analyse and understand emerging trends and issues Inform the development of mitigation strategies and solutions
    Translate data and produce visualisations to present findingsShare intelligence to support capability growth in a high performing team
    Skills and experience Gathers, investigates and analyses data and information Formats data and communicates results to the target audience
    Provides strong technical advice to resolve identified issues Builds strong relationships with business to achieve outcomes
    Benefits Attractive superannuation contributions of 15.4% Award-winning and highly professional organisation Contemporary workspaces and technology
    Learning and development opportunities These roles will be offered in Adelaide, Albury, Melbourne CBD, Moonee Ponds, Parramatta or Penrith.
    You must be an Australian citizen to work with the ATO. Does this sound like you? If this sounds like you, we encourage you to click “Apply”. Don’t forget to mention you applied through LinkedIn on your application.
    Find out more information about us on our careers page at www.ato.gov.au/careers""",

    "C":"""Do you want to join us in helping to fight the world's most threatening diseases and enabling access to care for more people around the world? At Siemens Healthineers, we pioneer breakthroughs in healthcare. For everyone. Everywhere.
    We offer you a flexible and dynamic environment with opportunities to go beyond your comfort zone in order to grow personally and professionally. Sound interesting?
    Then come and join our global team as a Data Engineer focused on enabling data driven decisions & self-service analytics for the business by provisioning & managing end-end architecture of Siemens Healthineers Australia & New Zealand Data Warehouse.
    Your tasks and responsibilities:Ownership of Data modelling and Data-warehousing for data serving layer.Design and implement from Multi model data warehouses.
    Responsible and accountable for pipelines reliability and availability and Data analysis for troubleshooting and exploration.
    Collaborate and maintain network with Data Scientists and Data Owners to assist with Data cataloguing and understanding the business context for data
    Your qualifications and experience: 5 years+ Experience in Design and implementation of robust end-to-end modern Data pipeline including sourcing and preparation.
    Experience in data integration, data transformation, evaluation of data quality & cleansing. Expert Knowledge of MS SQL, Snowflake and Python.
    Experience working with Analytics tools like Qlikview, Power BI is an added advantage. Your attributes and skills: Strong project management and analytical skills
    Our global team: We are a team of 66,000 highly dedicated employees across more than 70 countries passionately pushing the boundaries of what’s possible in healthcare to help improve people’s lives around the world. As a leader in the industry, we aspire to create better outcomes and experiences for patients no matter where they live or what health issues they are facing. Our portfolio, spanning from in-vitro and in-vivo diagnostics to image-guided therapy and innovative cancer care, is crucial for clinical decision-making and treatment pathways.
    Our culture: We are part of an incredible community of scientists, clinicians, developers, researchers, professionals, and skilled specialists pushing the boundaries of what’s possible, to improve people’s lives around the world. We embrace a culture of inclusivity in which the power and potential of every individual can be unleashed. We spark ideas that lead to positive impact and continued success.
    We are an equal opportunity employer. Applications close 31st of May or sooner should sufficient applications be received. We care about your data privacy and take compliance with GDPR as well as other data protection legislation seriously. For this reason, we ask you not to send us your CV or resume by email. We ask instead that you create a profile in our talent community where you can upload your CV. Setting up a profile lets us know you are interested in career opportunities with us and makes it easy for us to send you an alert when relevant positions become open.
    To all recruitment agencies: Siemens Healthineers does not accept agency resumes. Please do not forward resumes to our jobs alias, employees, or any other company location. Siemens Healthineers is not responsible for any fees related to unsolicited resumes.
    Organization: Siemens Healthineers Company: Siemens Healthcare Pty. Ltd. Experience Level: Experienced ProfessionalJob Type: Full-time""",

}
